### ISSUE TITLE
合法域名校验出错

### ISSUE THREAD

**Issue by inwalking** [WildDogTeam/wilddog-weapp#1]
asdebug.js:1  wss://s-dal5-nss-3.wilddogio.com:443/.ws/?v=1.0&cv=2.1.0&ns=walk-test001&EIO=3&transport=websocket 不在以下合法域名列表中，请参考文档：https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.html

微信端配置如下：
request合法域名	
https://auth.wilddog.com
socket合法域名	
wss://s-dalwx-nss-1.wilddogio.com
wss://walk-test001.wilddogio.com

**Comment by stackOverMind** [comment]
应该是版本过低的原因，可以试试现在的2.3.8

**Comment by inwalking** [comment]
嗯，更新后解决问题了，多谢
