### ISSUE TITLE
auth.signInWeapp()报错

### ISSUE THREAD

**Issue by inwalking** [WildDogTeam/wilddog-weapp#4]
> 请使用 encryptedData 和 iv 字段进行解密，详见：https://mp.weixin.qq.com/debug/wxadoc/dev/api/open.html

> 
> Error: [object Object]
>     at Error (native)
>     at success (http://562171007.appservice.open.weixin.qq.com/utils/wilddog-weapp-all.js:1233:80)
>     at Object.success (http://562171007.appservice.open.weixin.qq.com/WAService.js:3:7222)
>     at .<anonymous> (http://562171007.appservice.open.weixin.qq.com/WAService.js:4:20571)
>     at .<anonymous> (http://562171007.appservice.open.weixin.qq.com/asdebug.js:1:14728)
>     at http://562171007.appservice.open.weixin.qq.com/WAService.js:3:7222

**Comment by dongkai1993-zz** [comment]
你好！经测试 signInWeapp 没有出现报错的情况，如仍未解决，可以将代码粘贴上。

**Comment by inwalking** [comment]
嗯，谢谢，我更新了wilddog-weapp-all.js，问题仍未解决。
（sync().ref()使用正常，直接调用wx.login也正常）

app.js:
```
  userAuth: function () {
    wilddog.auth().signInWeapp(function (err, user) {
      console.log('called wilddog auth()')
      console.log(err);
      console.log(user);
    })
  },
```
console.js:
```
  btnGetUserInfo: function () {
    app.userAuth();
  }
```

Console Log:

> 请使用 encryptedData 和 iv 字段进行解密，详见：https://mp.weixin.qq.com/debug/wxadoc/dev/api/open.html
> app.js [sm]:19 called wilddog auth()
> app.js [sm]:20 Error: [object Object]
>     at Error (native)
>     at success (http://562171007.appservice.open.weixin.qq.com/utils/wilddog-weapp-all.js:1233:80)
>     at Object.success (http://562171007.appservice.open.weixin.qq.com/WAService.js:3:7222)
>     at .<anonymous> (http://562171007.appservice.open.weixin.qq.com/WAService.js:4:20571)
>     at .<anonymous> (http://562171007.appservice.open.weixin.qq.com/asdebug.js:1:14728)
>     at http://562171007.appservice.open.weixin.qq.com/WAService.js:3:7222
> app.js [sm]:21 undefined

**Comment by dongkai1993-zz** [comment]
https://docs.wilddog.com/sync/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F/quickstart.html#2-前期准备
前期准备工作是否都做了？

**Comment by inwalking** [comment]
Double checked, 没有发现问题。

> 1.在控制面板中创建应用。请参考 控制面板-创建应用。

Done, ref( ) 功能可正常使用

> 2.在 微信公众开放平台管理中心 设置—开发设置—服务器配置，配置域名白名单。为了简化配置，你需要增加以下 2 个域名到白名单：
> socket 合法域名： wss://s-dalwx-nss-1.wilddogio.com
> request 合法域名：https://auth.wilddog.com

Done, 微信后台未提示白名单报错

> 3.在 微信公众开放平台管理中心，获取应用的 AppID 和 AppSecret。

Done

> 4.在控制面板 身份认证—登录方式 中打开微信小程序登录授权开关，配置微信小程序 AppID 和 AppSecret。

Done, 尝试使用该ID和密钥直接request https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code, 顺利返回结果。

报错所在行代码如下，供参考
```
wx.request({ url: b, method: "POST", header: { Accept: "application/json;text/plain" }, success: function success(a) {
          a.data ? null != a.data.idToken ? c(null, a.data) : a.data.error ? c(Error(a.data.error)) : c(Error("unkown error:" + a.data)) : c(Error("unkown error: no data returned"));c = null;
        }, 
```

**Comment by dongkai1993-zz** [comment]
方便的话提供一下 wilddog appId 和 AppID AppSecret，我们的测试帐号一直没能复现该问题

**Comment by inwalking** [comment]
最近报错内容变了，如下

> WAService.js:3 thirdScriptError
> This custom Wilddog server ('undefined') does not support delegated login.;at App userAuth function
> Error: This custom Wilddog server ('undefined') does not support delegated login.
>     at Error (native)
>     at od (http://562171007.appservice.open.weixin.qq.com/utils/wilddog-weapp-all.js:2130:55)
>     at qd (http://562171007.appservice.open.weixin.qq.com/utils/wilddog-weapp-all.js:2037:7)
>     at N.Hg (http://562171007.appservice.open.weixin.qq.com/utils/wilddog-weapp-all.js:2295:133)
>     at e.userAuth (http://562171007.appservice.open.weixin.qq.com/app.js:21:20)
>     at e.<anonymous> (http://562171007.appservice.open.weixin.qq.com/WAService.js:7:1950)
>     at e.btnGetUserInfo (http://562171007.appservice.open.weixin.qq.com/pages/console/console.js:33:9)
>     at e.<anonymous> (http://562171007.appservice.open.weixin.qq.com/WAService.js:6:21930)
>     at e.a (http://562171007.appservice.open.weixin.qq.com/WAService.js:6:16691)
>     at I (http://562171007.appservice.open.weixin.qq.com/WAService.js:6:12938)

对应代码端如下：
`    if (a.Sb.ef && "auth.wilddog.com" === Fa) throw Error("This custom Wilddog server ('" + a.Sb.domain + "') does not support delegated login.");`

**Comment by inwalking** [comment]
appID: wx961c4c7240d21ae8
appSecret: 7de2cc01689d5ca02f2b899c813972ea
wilddogAPPID: walk-test001

**Comment by dongkai1993-zz** [comment]
`//app.js
var wilddog=require("wilddog-weapp-all");

App({
  onLaunch: function () {
    var config = {
    syncURL: 'https://<appId>.wilddogio.com',
    authDomain: '<appId>.wilddog.com'
}
wilddog.initializeApp(config);
wilddog.auth().signInWeapp(function(user,err){console.log(user,err)}).then(function(user){
  console.log(user);
}).catch(function(err){
  console.log(JSON.stringify(err.message));
})
  },
  globalData:{
    userInfo:null
  }
})`

我们使用这段代码测试过，成功通过了测试。

如果仍未解决，请加入野狗官方讨论群：534704506，群主将会帮你找原因。
